#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   bash scripts/setup-api-split-routing.sh
#
# Optional env vars:
#   PROJECT_DIR=/root/apps/life-design-backend
#   LEGACY_PORT=3000
#   GROWTH_PORT=3880
#   NGINX_SITE_FILE=/etc/nginx/sites-enabled/default
#   API_SERVER_NAME=api.life-design.me
#   PUBLIC_HOST=123.56.17.118

PROJECT_DIR="${PROJECT_DIR:-/root/apps/life-design-backend}"
LEGACY_PORT="${LEGACY_PORT:-3000}"
GROWTH_PORT="${GROWTH_PORT:-3880}"
NGINX_SITE_FILE="${NGINX_SITE_FILE:-/etc/nginx/sites-enabled/life-design}"
API_SERVER_NAME="${API_SERVER_NAME:-api.life-design.me}"
PUBLIC_HOST="${PUBLIC_HOST:-123.56.17.118}"
SNIPPET_FILE="/etc/nginx/snippets/life-design-api-split-locations.conf"

echo "==> 1) Checking required commands"
for cmd in pm2 nginx node npm; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "Missing command: $cmd"
    exit 1
  fi
done

echo "==> 2) Installing dependencies in $PROJECT_DIR"
cd "$PROJECT_DIR"
npm install

echo "==> 3) Ensuring legacy app on :$LEGACY_PORT (src/server.js)"
if pm2 describe life-design-backend >/dev/null 2>&1; then
  PORT="$LEGACY_PORT" pm2 restart life-design-backend --update-env
else
  PORT="$LEGACY_PORT" pm2 start "node src/server.js" \
    --name life-design-backend \
    --cwd "$PROJECT_DIR"
fi

echo "==> 4) Starting growth app on :$GROWTH_PORT (src/server.ts)"
pm2 delete life-design-growth >/dev/null 2>&1 || true
PORT="$GROWTH_PORT" pm2 start "node --import tsx src/server.ts" \
  --name life-design-growth \
  --cwd "$PROJECT_DIR"
pm2 save

echo "==> 5) Writing nginx split-routing snippet"
mkdir -p /etc/nginx/snippets
cat > "$SNIPPET_FILE" <<EOF
# Auto-generated by scripts/setup-api-split-routing.sh
# growth/upload-image -> new app (:${GROWTH_PORT})
# other routes keep existing upstream (:${LEGACY_PORT})

location ^~ /uploads/ {
    alias /root/apps/life-design-backend/uploads/;
    expires 7d;
    add_header Cache-Control "public";
    access_log off;
}

location ^~ /api/growth/ {
    proxy_pass http://127.0.0.1:${GROWTH_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}

location = /api/upload/image {
    proxy_pass http://127.0.0.1:${GROWTH_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}

location = /api/upload/images {
    proxy_pass http://127.0.0.1:${GROWTH_PORT};
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF

if [[ ! -f "$NGINX_SITE_FILE" ]]; then
  echo "Nginx site file not found: $NGINX_SITE_FILE"
  echo "Please set NGINX_SITE_FILE and re-run."
  exit 1
fi

echo "==> 6) Injecting include into nginx site config (if missing)"
mkdir -p /etc/nginx/sites-available/backups
for stale in "$NGINX_SITE_FILE".bak.* /etc/nginx/sites-enabled/*.bak.*; do
  [ -e "$stale" ] && mv "$stale" /etc/nginx/sites-available/backups/
done

if ! grep -q "include $SNIPPET_FILE;" "$NGINX_SITE_FILE"; then
  cp "$NGINX_SITE_FILE" "${NGINX_SITE_FILE}.bak.$(date +%F-%H%M%S)"
  awk -v snippet="    include ${SNIPPET_FILE};" '
    /server_name life-design\.me www\.life-design\.me;$/ && !main_done {
      print; print snippet; main_done=1; next
    }
    /server_name api\.life-design\.me;$/ && !api_done {
      print; print snippet; api_done=1; next
    }
    { print }
  ' "$NGINX_SITE_FILE" > "${NGINX_SITE_FILE}.tmp" && mv "${NGINX_SITE_FILE}.tmp" "$NGINX_SITE_FILE"
fi

echo "==> 7) Reloading nginx"
nginx -t
systemctl reload nginx

echo "==> 8) Quick smoke checks"
echo "--- PM2 status ---"
pm2 status
echo "--- Port listeners ---"
ss -lntp | awk '$4 ~ /:3000$|:3001$|:3880$/'

echo "--- Public checks (${PUBLIC_HOST}:3000) ---"
curl -sS -i "http://${PUBLIC_HOST}:3000/health" | sed -n '1,14p'
echo "---"
curl -sS -i "http://${PUBLIC_HOST}:3000/api/growth/cms/articles" | sed -n '1,20p'

echo
echo "Done."
echo "If /api/growth/cms/articles is still not 200, check:"
echo "  1) nginx -T | grep -n \"${SNIPPET_FILE//\//\\/}\""
echo "  2) pm2 logs life-design-growth --lines 80"
echo "  3) pm2 logs life-design-legacy --lines 80"
